# Route sans bundle
index:
    path: /
    defaults: 
        # Controller:Methode
        _controller: home:index

# Route avec bundle
## Exemple de route : https://domaine.com/test/username/42
nom_de_ma_route_exemple:
    path: /test/{username}/{id}
    defaults: 
        # Bundle:Controller:Methode
        _controller: Test:Test:index
    requirements:
        username: "[a-zA-Z0-9_-]{2,150}"
        id: "[0-9]{2}"
        # option facultative, GET par défaut
        _method:  GET

# Importer un fichier route. On indique le nom du fichier sans le .yml
# toujours le mettre à la fin.
import@: 
   - errors
